### ISSUE TITLE
Arduino and 5V/GND

### ISSUE THREAD

**Issue by vincentbernat** [DhrBaksteen/ArduinoOPL2#16]
Hey!

Looking at the assembly instruction, I wonder why 5V/GND are not mentioned on Arduino. Shouldn't they be wired?

**Comment by DhrBaksteen** [comment]
Yes they must be wired. 

To me it seemed more obvious for an Arduino since the pins are nicely labeled on the board, wherace a Raspberry Pi just has the bare pin headers. That's why I didn't bother for the Arduino :).

**Comment by vincentbernat** [comment]
OK, thanks. Sorry for the dumb question!
