### ISSUE TITLE
Default configuration is inconsistent with documentation

### ISSUE THREAD

**Issue by maxime-esa** [DhrBaksteen/ArduinoOPL2#26]
This line :

https://github.com/DhrBaksteen/ArduinoOPL2/blob/master/src/OPL2.cpp#L37

states:
```Make sure you set the correct BOARD_TYPE in OPL2.h. Default is set to Arduino```

but this is actually incorrect, as you can see here:

https://github.com/DhrBaksteen/ArduinoOPL2/blob/master/src/OPL2.h#L24

```#define BOARD_TYPE RASPBERRY_PI```

The immediate consequence is that the build with the Arduino IDE fails when you first follow the testing instructions. It's a easy to spot, but better keep the comment consistent with the actual code.

Thank you for this amazing board!

**Comment by DhrBaksteen** [comment]
Thanks for mentioning this. The default board type should've been `ARDUINO`. I must have forgotten to change it back after the last tests on a pi :(. A new release is available and should be picked up by Arduino's library manager within a few hours.

I need to setup a pre-commit hook to catch these kinds of mistakes...
