### ISSUE TITLE
No License Specified

### ISSUE THREAD

**Issue by NathanSchenk** [DhrBaksteen/ArduinoOPL2#4]
DhrBaksteen,

I would like to use this library as a starting point for a project I am working on.  Since you don't have a license file specified, I am unsure if I can use this for my project.

Would you consider adding an open source license designation to this project such as the MIT license?

Thanks for your hard work!

**Comment by DhrBaksteen** [comment]
Hi Nathan,

This project is open source so feel free to use the code for your own project. I will look into what licence would be the most appropriate for this project and add it.

Cheers,
Maarten

**Comment by DhrBaksteen** [comment]
MIT license added to the project
