### ISSUE TITLE
Replacement for 10µF capacitors for breadboard?

### ISSUE THREAD

**Issue by StarWolf3000** [DhrBaksteen/ArduinoOPL2#52]
Hi,

before I'm going to gather and assemble everything on a PCB, I want to test the whole construct on a breadboard. Unfortunately, the only components I'm unable to get my hands on are the 10µF capacitors (not the electrolytic ones), C1 to C4 in the schematic/components list, for use on a breadboard.

Can they be substituted with some other capacitors or can I use electrolytic or tantal ones, with paying attention to the polarity?

**Comment by DhrBaksteen** [comment]
Hi,

You can also use regular electrolytic ones for C1 .. C4. For C1, C3 and C4 the negative pin is connected directly to ground. For C2 the + side is connected to R1 and the - side to VR1.
