### ISSUE TITLE
Gerber files ?

### ISSUE THREAD

**Issue by Tesseract-runner** [DhrBaksteen/ArduinoOPL2#96]
Hello, thanks for sharing this cool board !
Unfortunately, the shipping fees to my country are prohibitively expensive.
Could you share the Gerber files so I can order the PCB from an online manufacturer.
Regards

**Comment by DhrBaksteen** [comment]
Please don't raise issues that are unrleated to the OPL2 Library.

Sorry, gerber files are not shared. The schematics are included in the library, you can use it if you want to design your own PCB.

**Comment by Tesseract-runner** [comment]
Sorry !
